public class Problem2 
{
	public static void main(String[] args) 
	{
		/*
			Each new term in the Fibonacci sequence is generated by adding
			the previous two terms. By starting with 1 and 2, the first 10
			terms will be:
				1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
			By considering the terms in the Fibonacci sequence whose values do
			not exceed four million, find the sum of the even-valued terms.

			Answer = 4613732
		*/
		// Fastest way to do it I think
		int temp1 = 0;
		int temp2 = 1;
		int sum = 0;
		while (temp2 <= 4000000) {
			int next = temp1 + temp2;
			temp1 = temp2;
			temp2 = next;
			if (temp2 % 2 == 0) {
				sum += temp2;
			}
		}

		System.out.println(sum);
	}
}