import java.util.ArrayList;

public class Problem45
{
	public static void main(String[] args)
	{
		/*
		Triangle, pentagonal, and hexagonal numbers are generated by the
		following formulae:

		Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
		Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
		Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
		It can be verified that T285 = P165 = H143 = 40755.

		Find the next triangle number that is also pentagonal and hexagonal.

		Answer=1533776805
		*/
		int inc = 286;
		int count = 0;
		while (true) {
			long triangle = getTriangleNumber(inc);
			if (isPentagonal(triangle) && isHexagonal(triangle)) {
				System.out.println(triangle);
				return;
			}
			inc++;
		}
	}

	public static boolean isPentagonal(long num)
	{
		num *= 2;

		long n = 1;
		long tmp = 3 * (n * n) - n - num;
		while (tmp < 0) {
			n++;
			tmp = 3 * (n * n) - n - num;
		}
		return (tmp == 0);
	}

	public static boolean isHexagonal(long num)
	{
		// Hn = n(2n - 1)
		// Hn = 2n^2 - n
		// 0 = 2n^2 - n - num
		long n = 1;
		long tmp = 2 * (n * n) - n - num;
		while (tmp < 0) {
			n++;
			tmp = 2 * (n * n) - n - num;
		}
		return (tmp == 0);

	}

	public static long getTriangleNumber(long n)
	{
		return (n * (n + 1)) / 2;
	}
}